### ISSUE TITLE
Uncaught TypeError: setEditorState is not a function

### ISSUE THREAD

**Issue by philohelp** [andrey-semin/draft-js-list-shortcut-plugin#1]
Hello,

I get this error when I try to use the plugin : 

<img width="454" alt="Capture d’écran 2019-09-06 à 21 07 47" src="https://user-images.githubusercontent.com/12623963/64454183-a0c99180-d0ea-11e9-9173-388263fa031d.png">

Here is my package.json : 
    "draft-js": "^0.11.0",
    "draft-js-plugins-editor": "^3.0.0",
    "draft-js-list-shortcut-plugin": "^1.0.1"

I get the same error with the autolist plugin...

**Comment by andrey-semin** [comment]
@philohelp sorry for late response! I wrote an answer back in September but for some reason it wasn't published, maybe there was an error with my connection. It seems like you configure the plugin in a wrong way. Can you share the snipper of the code that results in an error?

**Comment by seansen** [comment]
@philohelp - use the forth parameter for draftjs 0.11.0
https://github.com/draft-js-plugins/draft-js-plugins/issues/1291#issuecomment-520656915

**Comment by philohelp** [comment]
Many thanks !
